name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04]
        arch: [arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Set up QEMU
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          
      - name: Build and Test
        run: |
          dotnet restore
          dotnet build -c Release
          dotnet test

      - name: Publish Artifact
        if: success()
        run: |
          mkdir -p dist
          dotnet publish -c Release -o dist

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: dist
